# Generated by Django 5.2.4 on 2025-07-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_blog_remove_comment_user_remove_singer_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='origin_url',
            field=models.URLField(blank=True, null=True, verbose_name='歌曲原始URL'),
        ),
        migrations.AddField(
            model_name='song',
            name='origin_url',
            field=models.URLField(blank=True, null=True, verbose_name='歌手原始URL'),
        ),
    ]
